DROP TABLE IF EXISTS characters CASCADE;
DROP TABLE IF EXISTS quotes;
DROP TABLE IF EXISTS chickens;

CREATE TABLE characters (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(512) UNIQUE NOT NULL,
    full_name VARCHAR(512) NOT NULL,
    aliases VARCHAR(512),
    pic VARCHAR(2000) NOT NULL,
    actor VARCHAR(256) NOT NULL
);

CREATE TABLE quotes (
    id SERIAL PRIMARY KEY NOT NULL,
    quote VARCHAR(512) NOT NULL,
    said_by VARCHAR(512) NOT NULL REFERENCES characters(name)
);

CREATE TABLE chickens (
    id SERIAL PRIMARY KEY NOT NULL,
    url VARCHAR(512) NOT NULL
);
